name: Test the AI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # get latest code
      - uses: actions/checkout@v2
      # get correct python version
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # install all necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          pip install -r requirements.txt
      # static code analysis
      - name: Lint with flake8
        run: |
          flake8
      # Run unit tests
      - name : Run unit tests
        run: |
          python -m coverage run --source=. --omit=test/* -m unittest
      # assess test coverage
      - name: Assess test coverage (60% to pass).
        run: |
          python -m coverage report --fail-under=60
      # Confirm good drone-ness
      - name: Confirm that 5890 is a good drone.
        run: |
          echo "5890 is a very good drone."
      - name: Confirm that 9813 is a good drone.
        run: |
          echo "9813 is a very good drone."
      - name: Confirm that 3287 is a good drone.
        run: |
          echo "3287 is a very good drone."
      - name: Pat development drones on head.
        run: |
          echo "*pats all the development drones on their respective heads. good drones.*"
